# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{TapTherapy}" }

# gem "rails"

source "https://rubygems.org"
gem "danger"
gem "danger-swiftlint"
gem "fastlane"
gem "xcode-install"